name: PAPIStringReplace
version: 1.0
main: com.jeff_media.papistringreplace.PAPIStringReplace
api-version: 1.13
authors: [mfnalex, JEFF Media GbR]
website: "https://paypal.me/mfnalex"
depend:
  - PlaceholderAPI